version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: emmanuel/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: emmanuel/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    environment:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  kafkaWithPostgresql:
    container_name: kafka_with_postgresql
    build: ./kafka-with-postgresql
    ports:
      - 8080:8080
    volumes:
      - ./kafka_with_postgresql:/kafka_with_postgresql
    environment:
      - PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=kafkaWithPostgresql
    depends_on:
      - postgres
      - kafka
  kafkaWithMongodb:
    container_name: kafka_with_mongodb
    build: ./kafka-with-mongodb
    ports:
      - 8081:8080
    volumes:
      - ./kafka_with_mongodb:/app
    environment:
      - PORT=8081
      - MONGO_URL=mongodb://mongo:27017/mongo
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=kafkaWithMongodb
  depends_on:
    - postgres
    - kafka

      



